'use client';

import React, { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { formatCurrencyNPR } from '@/lib/nepali-date';
import { useToast } from '@/lib/toast-context';
import { useAutoSync } from '@/lib/sync';
import Link from 'next/link';

export default function TenantBillsPage() {
  const toast = useToast();
  const [bills, setBills] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedBill, setSelectedBill] = useState<any>(null);

  const loadBills = async (isBackground = false) => {
    try {
      if (!isBackground) setLoading(true);
      const data = await api.get('/billing/my-history');
      setBills(Array.isArray(data) ? data : []);
    } catch (err: any) {
      if (!isBackground) toast.error(err.message || 'Failed to load billing history');
    } finally {
      if (!isBackground) setLoading(false);
    }
  };

  useEffect(() => {
    loadBills();
  }, []);

  // Real-time synchronization for tenant bills
  useAutoSync(() => loadBills(true), ['bill', 'payment', 'electricity', 'water', 'all']);

  const handleOpenBillDetails = async (b: any) => {
    setSelectedBill(b);
    try {
      const full = await api.get(`/billing/${b.id}`);
      setSelectedBill(full);
    } catch (e) {
      // fallback to b
    }
  };

  return (
    <div className="space-y-6 text-xs">
      <div className="flex items-center justify-between pb-3 border-b border-slate-200">
        <div>
          <h1 className="text-base font-bold text-slate-900">Billing History</h1>
          <p className="text-xs text-slate-500">All monthly invoices, electricity consumption records, and balances</p>
        </div>
        <div className="flex items-center gap-2">
          <Link
            href="/tenant/receipts"
            className="px-3 py-1.5 rounded-lg border border-slate-300 hover:bg-slate-100 text-slate-700 font-semibold text-xs transition"
          >
            Digital Receipts
          </Link>
          <Link
            href="/tenant/pay"
            className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs transition shadow-sm"
          >
            Pay Bill
          </Link>
        </div>
      </div>

      {loading ? (
        <div className="bg-white border border-slate-200 rounded-xl p-12 text-center text-slate-400">
          Loading billing records...
        </div>
      ) : bills.length === 0 ? (
        <div className="bg-white border border-slate-200 rounded-xl p-10 text-center text-slate-500 shadow-sm">
          <p className="font-semibold text-slate-900">No bills in history</p>
          <p className="text-xs text-slate-400 mt-1">Monthly bills will appear here once generated by the owner.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {bills.map((b) => {
            const isPaid = b.status === 'PAID' || b.balanceDue === 0;
            const isPending = !isPaid && b.status === 'PENDING_VERIFICATION';
            const isPartial = !isPaid && !isPending && b.paidAmount > 0;
            const elec = b.electricityReading;

            return (
              <div
                key={b.id}
                className="bg-white border border-slate-200 rounded-xl p-4 sm:p-5 shadow-sm space-y-3.5"
              >
                {/* Header Row */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-sm text-slate-900">
                        {b.billingPeriodBS || `${b.yearBS} ${b.monthNameBS}`}
                      </span>
                      {b.isOngoing && (
                        <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-amber-50 text-amber-800 border border-amber-200">
                          Ongoing
                        </span>
                      )}
                    </div>
                    <div className="text-[11px] text-slate-400 font-mono mt-0.5">
                      Bill No: {b.billNumber} {b.correctionReason && <span className="text-amber-700 ml-1 font-sans italic">(Corrected: {b.correctionReason})</span>}
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    {isPaid && (
                      <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                        Paid
                      </span>
                    )}
                    {isPending && (
                      <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-amber-50 text-amber-800 border border-amber-200">
                        Verification Pending
                      </span>
                    )}
                    {isPartial && (
                      <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-blue-50 text-blue-700 border border-blue-200">
                        Partially Paid
                      </span>
                    )}
                    {!isPaid && !isPending && !isPartial && (
                      <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-rose-50 text-rose-700 border border-rose-200">
                        Unpaid
                      </span>
                    )}
                  </div>
                </div>

                {/* Electricity Reading Summary Bar */}
                <div className="bg-slate-50 rounded-lg p-2.5 border border-slate-200 text-[11px] flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-1.5 font-semibold text-slate-900">
                    <svg className="w-3.5 h-3.5 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    <span>Meter:</span>
                    <span className="font-mono text-slate-700">
                      {elec?.previousReading ?? '—'} &rarr; {elec?.currentReading ?? '—'}
                    </span>
                    <span className="text-slate-500 font-normal">
                      ({elec?.unitsUsed ?? 0} units @ Rs. {elec?.unitRate ?? 15})
                    </span>
                  </div>

                  <div className="font-mono font-semibold text-slate-900">
                    Electricity: {formatCurrencyNPR(b.electricityAmount)}
                  </div>
                </div>

                {/* Charges & Action Row */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-1">
                  <div className="flex flex-wrap gap-4 text-xs">
                    <div>
                      <span className="text-slate-500 text-[11px]">Room Rent:</span>{' '}
                      <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(b.rentAmount)}</span>
                    </div>
                    {b.customPurchasesAmount > 0 && (
                      <div>
                        <span className="text-slate-500 text-[11px]">Custom Items:</span>{' '}
                        <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(b.customPurchasesAmount)}</span>
                      </div>
                    )}
                    <div>
                      <span className="text-slate-500 text-[11px]">Total Bill:</span>{' '}
                      <span className="font-mono font-bold text-slate-900">{formatCurrencyNPR(b.totalAmount)}</span>
                    </div>
                    <div>
                      <span className="text-slate-500 text-[11px]">Paid:</span>{' '}
                      <span className="font-mono font-semibold text-emerald-700">{formatCurrencyNPR(b.paidAmount)}</span>
                    </div>
                    <div>
                      <span className="text-slate-500 text-[11px]">Remaining Due:</span>{' '}
                      <span className="font-mono font-bold text-rose-700">{formatCurrencyNPR(b.balanceDue)}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 self-start sm:self-center">
                    <button
                      onClick={() => handleOpenBillDetails(b)}
                      className="px-2.5 py-1.5 rounded-lg border border-slate-300 hover:bg-slate-50 text-slate-700 font-medium text-xs transition"
                    >
                      Full Details
                    </button>

                    {b.balanceDue > 0 && b.status !== 'PENDING_VERIFICATION' && (
                      <Link
                        href="/tenant/pay"
                        className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs transition shadow-sm"
                      >
                        Pay Due
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Full Details Modal */}
      {selectedBill && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs animate-in fade-in">
          <div className="w-full max-w-md bg-white border border-slate-200 rounded-xl p-5 shadow-2xl space-y-4 text-xs max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div>
                <h3 className="font-bold text-sm text-slate-900">
                  {selectedBill.billingPeriodBS || `${selectedBill.yearBS} ${selectedBill.monthNameBS}`}
                </h3>
                <p className="text-[11px] text-slate-500 font-mono">Bill No: {selectedBill.billNumber}</p>
              </div>
              <button
                onClick={() => setSelectedBill(null)}
                className="w-6 h-6 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-700 flex items-center justify-center font-bold"
              >
                &times;
              </button>
            </div>

            {/* Electricity Breakdown */}
            <div className="bg-slate-50 rounded-lg p-3 border border-slate-200 space-y-1.5">
              <span className="font-bold text-slate-900 block text-xs">Electricity Consumption</span>
              <div className="grid grid-cols-2 gap-2 text-[11px]">
                <div><span className="text-slate-500">Prev Reading:</span> <span className="font-mono font-medium text-slate-900">{selectedBill.electricityReading?.previousReading ?? '—'}</span></div>
                <div><span className="text-slate-500">Curr Reading:</span> <span className="font-mono font-medium text-slate-900">{selectedBill.electricityReading?.currentReading ?? '—'}</span></div>
                <div><span className="text-slate-500">Units Consumed:</span> <span className="font-mono font-medium text-slate-900">{selectedBill.electricityReading?.unitsUsed ?? 0} units</span></div>
                <div><span className="text-slate-500">Unit Rate:</span> <span className="font-mono font-medium text-slate-900">Rs. {selectedBill.electricityReading?.unitRate ?? 15}</span></div>
              </div>
              <div className="flex justify-between pt-1 border-t border-slate-200/60 font-semibold text-slate-900">
                <span>Electricity Charge:</span>
                <span className="font-mono">{formatCurrencyNPR(selectedBill.electricityAmount)}</span>
              </div>
            </div>

            {/* Full Line Items */}
            <div className="space-y-1.5 text-slate-700">
              <span className="font-bold text-slate-500 uppercase tracking-wider text-[10px]">All Line Items</span>
              <div className="flex justify-between py-1 border-b border-slate-50">
                <span>1. Room Rent</span>
                <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(selectedBill.rentAmount)}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-50">
                <span>2. Internet Charge</span>
                <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(selectedBill.internetAmount)}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-50">
                <span>3. Garbage Charge</span>
                <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(selectedBill.garbageAmount ?? 100)}</span>
              </div>
              {selectedBill.waterAmount > 0 && (
                <div className="flex justify-between py-1 border-b border-slate-50">
                  <span>4. Drinking Water</span>
                  <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(selectedBill.waterAmount)}</span>
                </div>
              )}
              {selectedBill.customPurchasesAmount > 0 && (
                <div className="py-1 border-b border-slate-50 space-y-1">
                  <div className="flex justify-between">
                    <span className="font-semibold text-slate-900">5. Custom Purchases / Extra Charges:</span>
                    <span className="font-mono font-bold text-slate-900">{formatCurrencyNPR(selectedBill.customPurchasesAmount)}</span>
                  </div>
                  {selectedBill.breakdown?.customPurchases?.items && selectedBill.breakdown.customPurchases.items.length > 0 && (
                    <div className="text-[11px] text-slate-500 bg-slate-50 p-2 rounded border border-slate-200/70 space-y-1">
                      {selectedBill.breakdown.customPurchases.items.map((item: any) => (
                        <div key={item.id} className="flex justify-between items-center">
                          <div>
                            <span className="font-medium text-slate-800">{item.itemName}</span>
                            <span className="text-slate-500"> &times; {item.quantity} @ Rs. {item.unitPrice}</span>
                            {item.purchaseDateBS && <span className="text-[10px] text-slate-400 ml-1">({item.purchaseDateBS})</span>}
                            {item.note && <div className="text-[10px] text-slate-400 italic">{item.note}</div>}
                          </div>
                          <span className="font-mono font-semibold text-slate-900">{formatCurrencyNPR(item.totalAmount)}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {selectedBill.adjustmentsAmount !== 0 && (
                <div className="flex justify-between py-1 border-b border-slate-50">
                  <span>6. Adjustments</span>
                  <span className="font-mono font-medium text-slate-900">{formatCurrencyNPR(selectedBill.adjustmentsAmount)}</span>
                </div>
              )}

              <div className="pt-2 border-t border-slate-200 flex justify-between items-center text-xs font-bold text-slate-900">
                <span>Total Calculated Bill:</span>
                <span className="font-mono">{formatCurrencyNPR(selectedBill.totalAmount)}</span>
              </div>
              <div className="flex justify-between items-center text-emerald-700">
                <span>Paid So Far:</span>
                <span className="font-mono font-semibold">{formatCurrencyNPR(selectedBill.paidAmount)}</span>
              </div>
              <div className="flex justify-between items-center text-xs font-bold text-rose-700">
                <span>Remaining Balance Due:</span>
                <span className="font-mono">{formatCurrencyNPR(selectedBill.balanceDue)}</span>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-slate-100">
              <button
                onClick={() => setSelectedBill(null)}
                className="px-3.5 py-1.5 rounded-lg border border-slate-300 text-slate-700 hover:bg-slate-50 font-medium"
              >
                Close
              </button>
              {selectedBill.balanceDue > 0 && selectedBill.status !== 'PENDING_VERIFICATION' && (
                <Link
                  href="/tenant/pay"
                  className="px-3.5 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-white font-medium shadow-sm"
                >
                  Pay Outstanding
                </Link>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
